# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
import datetime
from collections.abc import AsyncIterator
from uuid import UUID
from zoneinfo import ZoneInfo

import pytest
from _pytest.monkeypatch import MonkeyPatch
from fastapi import FastAPI
from httpx import AsyncClient
from pydantic import BaseModel

from safetynet.autogenerated_graphql_client import GraphQLClient
from safetynet.main import GRAPHQL_VERSION
from safetynet.main import create_app
from safetynet.types import CPRNumber

FROM_DATE = datetime.datetime(1990, 1, 1, tzinfo=ZoneInfo("Europe/Copenhagen"))


@pytest.fixture
async def app(monkeypatch: MonkeyPatch) -> FastAPI:
    """
    Override the FastRAMQPI plugin's `app` fixture (which raises
    NotImplementedError). Settings come from the environment (see
    docker-compose.yml); per-test overrides use `@pytest.mark.envvar({...})`.
    """
    app = create_app()
    return app


@pytest.fixture
async def graphql_client(mo_client: AsyncClient) -> AsyncIterator[GraphQLClient]:
    """Authenticated GraphQL codegen client for OS2mo.

    `mo_client` is provided by the FastRAMQPI pytest plugin (an authenticated
    httpx client pointed at the running MO stack).
    """
    graphql_client = GraphQLClient(
        url=f"{mo_client.base_url}/graphql/v{GRAPHQL_VERSION}",
        http_client=mo_client,
    )
    async with graphql_client as client:
        yield client


class MOClass(BaseModel):
    """A class to create, and the facet to create it under."""

    facet: str
    user_key: str
    name: str


MO_CLASSES: list[MOClass] = [
    MOClass(
        facet="org_unit_type",
        user_key="Enhed",
        name="Enhed",
    ),
    MOClass(
        facet="engagement_type",
        user_key="fuldtid",
        name="Månedslønnet, fuldtid",
    ),
    # Deliberately *not* in `allowed_sd_engagement_types`, so that resolving an
    # SD manager engagement has to filter it out.
    MOClass(
        facet="engagement_type",
        user_key="timelønnet",
        name="Timelønnet",
    ),
    MOClass(
        facet="engagement_job_function",
        user_key="Ninja",
        name="Ninja",
    ),
    MOClass(
        facet="manager_type",
        user_key="leder",
        name="Leder",
    ),
    MOClass(
        facet="manager_level",
        user_key="afdelingsleder",
        name="Afdelingsleder",
    ),
    MOClass(
        facet="responsibility",
        user_key="personale",
        name="Personale",
    ),
    # The MED association role. Its *name* is what the report splits into one row
    # per role, so it is deliberately a composite role (Redmine case #63407).
    MOClass(
        facet="association_type",
        user_key="tr-naestformand",
        name="TR, næstformand",
    ),
    # The association's `trade_union`, which MO exposes as `dynamic_class` and
    # the MED association report emits as Hovedorganisation.
    MOClass(
        facet="trade_union",
        user_key="LO",
        name="LO",
    ),
]


@pytest.fixture
async def root_org(graphql_client: GraphQLClient) -> UUID:
    """Create MOs root organisation.

    The FastRAMQPI integration fixtures reset MO to an empty (migrated but
    unpopulated) database before every test, so nothing exists up front: the
    root organisation has to be created before any employee or org unit can be.
    """
    org = await graphql_client._testing__create_org()
    return org.uuid


@pytest.fixture
async def class_uuids(graphql_client: GraphQLClient, root_org: UUID) -> dict[str, UUID]:
    """Seed the facets and classes used for seeding the org trees.

    MO is empty at this point (see `root_org`), so the classes the trees are
    built from must be created here rather than looked up from MO fixtures.
    Returned keyed by class user_key, since a facet may hold more than one
    class; each facet itself is only created once.
    """
    facet_uuids: dict[str, UUID] = {}
    class_uuids = {}
    for mo_class in MO_CLASSES:
        if mo_class.facet not in facet_uuids:
            facet = await graphql_client._testing__create_facet(
                user_key=mo_class.facet, from_date=FROM_DATE
            )
            facet_uuids[mo_class.facet] = facet.uuid
        cls = await graphql_client._testing__create_class(
            user_key=mo_class.user_key,
            name=mo_class.name,
            facet_uuid=facet_uuids[mo_class.facet],
            from_date=FROM_DATE,
        )
        class_uuids[mo_class.user_key] = cls.uuid
    return class_uuids


async def _create_ou(
    gql: GraphQLClient,
    class_uuids: dict[str, UUID],
    name: str,
    user_key: str,
    parent: UUID | None = None,
) -> UUID:
    ou = await gql._testing__create_org_unit(
        name=name,
        user_key=user_key,
        org_unit_type=class_uuids["Enhed"],
        from_date=FROM_DATE,
        parent=parent,
    )
    return ou.uuid


async def _create_engagement(
    gql: GraphQLClient,
    class_uuids: dict[str, UUID],
    user_key: str,
    person: UUID,
    org_unit: UUID,
    engagement_type: UUID | None = None,
) -> UUID:
    engagement = await gql._testing__create_engagement(
        user_key=user_key,
        person=person,
        org_unit=org_unit,
        engagement_type=engagement_type or class_uuids["fuldtid"],
        job_function=class_uuids["Ninja"],
        from_date=FROM_DATE,
    )
    return engagement.uuid


async def _create_manager(
    gql: GraphQLClient,
    class_uuids: dict[str, UUID],
    user_key: str,
    person: UUID,
    org_unit: UUID,
    engagement: UUID | None = None,
) -> None:
    await gql._testing__create_manager(
        user_key=user_key,
        person=person,
        org_unit=org_unit,
        manager_type=class_uuids["leder"],
        manager_level=class_uuids["afdelingsleder"],
        responsibility=[class_uuids["personale"]],
        engagement=engagement,
        from_date=FROM_DATE,
    )


async def _create_association(
    gql: GraphQLClient,
    class_uuids: dict[str, UUID],
    user_key: str,
    person: UUID,
    org_unit: UUID,
    trade_union: UUID | None = None,
) -> UUID:
    association = await gql._testing__create_association(
        user_key=user_key,
        person=person,
        org_unit=org_unit,
        association_type=class_uuids["tr-naestformand"],
        trade_union=trade_union,
        from_date=FROM_DATE,
    )
    return association.uuid


@pytest.fixture
async def opus_tree(
    graphql_client: GraphQLClient, class_uuids: dict[str, UUID]
) -> UUID:
    """
    OPUS, manager is a different person than the employee being processed: the report
    uses the org-unit manager's user_key directly as the manager engagement number.
    """
    ou = await _create_ou(graphql_client, class_uuids, "SafetyNet OPUS", "sn_opus_root")
    employee = await graphql_client._testing__create_employee(
        given_name="Opus", surname="Employee", cpr_number=CPRNumber("2512480001")
    )
    await _create_engagement(graphql_client, class_uuids, "12345", employee.uuid, ou)
    manager = await graphql_client._testing__create_employee(
        given_name="Opus", surname="Manager", cpr_number=CPRNumber("2512480002")
    )
    await _create_manager(graphql_client, class_uuids, "54321", manager.uuid, ou)
    return ou


@pytest.fixture
async def opus_self_managed_tree(
    graphql_client: GraphQLClient, class_uuids: dict[str, UUID]
) -> UUID:
    """
    OPUS, the unit's manager IS the employee themselves: the report must fall
    back to the manager of the parent unit.
    """
    parent = await _create_ou(
        graphql_client, class_uuids, "OPUS parent", "sn_opus_parent"
    )
    parent_manager = await graphql_client._testing__create_employee(
        given_name="Opus", surname="ParentManager", cpr_number=CPRNumber("2512480005")
    )
    await _create_manager(
        graphql_client, class_uuids, "54321", parent_manager.uuid, parent
    )
    child = await _create_ou(
        graphql_client, class_uuids, "OPUS child", "sn_opus_child", parent=parent
    )
    employee = await graphql_client._testing__create_employee(
        given_name="Opus", surname="SelfManager", cpr_number=CPRNumber("2512480006")
    )
    await _create_engagement(graphql_client, class_uuids, "12345", employee.uuid, child)
    # The employee is also the manager of their own unit (same user_key).
    await _create_manager(graphql_client, class_uuids, "12345", employee.uuid, child)
    return child


@pytest.fixture
async def sd_tree(graphql_client: GraphQLClient, class_uuids: dict[str, UUID]) -> UUID:
    """
    SD, manager resolved via the manager role's linked engagement
    (`engagement_response`). The `XY-` InstitutionIdentifier prefix is stripped.
    """
    ou = await _create_ou(graphql_client, class_uuids, "SafetyNet SD", "sn_sd_root")
    employee = await graphql_client._testing__create_employee(
        given_name="Sd", surname="Employee", cpr_number=CPRNumber("2512480003")
    )
    await _create_engagement(graphql_client, class_uuids, "XY-55501", employee.uuid, ou)
    manager = await graphql_client._testing__create_employee(
        given_name="Sd", surname="Manager", cpr_number=CPRNumber("2512480004")
    )
    manager_engagement = await _create_engagement(
        graphql_client, class_uuids, "XY-55502", manager.uuid, ou
    )
    await _create_manager(
        graphql_client,
        class_uuids,
        "sd-mgr-role",
        manager.uuid,
        ou,
        engagement=manager_engagement,
    )
    return ou


@pytest.fixture
async def sd_fallback_tree(
    graphql_client: GraphQLClient, class_uuids: dict[str, UUID]
) -> UUID:
    """
    SD, manager role has no linked engagement (`engagement_response` is null), so
    the manager engagement is resolved by matching the manager's engagements
    against `allowed_sd_engagement_types` (left at its default, which contains
    "fuldtid" but not "timelønnet").

    The manager therefore has two engagements, only one of which is of an
    allowed type, so picking the right one actually depends on the filter.
    """
    ou = await _create_ou(graphql_client, class_uuids, "SD fallback", "sn_sd_fallback")
    employee = await graphql_client._testing__create_employee(
        given_name="Sd", surname="FbEmployee", cpr_number=CPRNumber("2512480007")
    )
    await _create_engagement(graphql_client, class_uuids, "XY-70001", employee.uuid, ou)
    manager = await graphql_client._testing__create_employee(
        given_name="Sd", surname="FbManager", cpr_number=CPRNumber("2512480008")
    )
    await _create_engagement(graphql_client, class_uuids, "XY-70002", manager.uuid, ou)
    await _create_engagement(
        graphql_client,
        class_uuids,
        "XY-70003",
        manager.uuid,
        ou,
        engagement_type=class_uuids["timelønnet"],
    )
    # No engagement link -> forces the allowed-engagement-type fallback.
    await _create_manager(graphql_client, class_uuids, "sd-fb-mgr", manager.uuid, ou)
    return ou


@pytest.fixture
async def sd_coupling_tree(
    graphql_client: GraphQLClient, class_uuids: dict[str, UUID]
) -> UUID:
    """
    SD, the manager has *multiple* candidate engagements (both matching the
    allowed types), so the ambiguous fallback would fail; the manager role's
    linked engagement (`engagement_response`) must take precedence.
    """
    ou = await _create_ou(graphql_client, class_uuids, "SD coupling", "sn_sd_coupling")
    employee = await graphql_client._testing__create_employee(
        given_name="Sd", surname="CplEmployee", cpr_number=CPRNumber("2512480009")
    )
    await _create_engagement(graphql_client, class_uuids, "XY-80001", employee.uuid, ou)
    manager = await graphql_client._testing__create_employee(
        given_name="Sd", surname="CplManager", cpr_number=CPRNumber("2512480010")
    )
    linked = await _create_engagement(
        graphql_client, class_uuids, "XY-80002", manager.uuid, ou
    )
    # A second engagement makes the fallback ambiguous; engagement_response wins.
    await _create_engagement(graphql_client, class_uuids, "XY-80003", manager.uuid, ou)
    await _create_manager(
        graphql_client, class_uuids, "sd-cpl-mgr", manager.uuid, ou, engagement=linked
    )
    return ou


@pytest.fixture
async def opus_unmanaged_tree(
    graphql_client: GraphQLClient, class_uuids: dict[str, UUID]
) -> UUID:
    """
    OPUS, the unit has no manager at all (and none to inherit from), so the
    report leaves the manager engagement number empty.
    """
    ou = await _create_ou(
        graphql_client, class_uuids, "OPUS unmanaged", "sn_opus_unmgd"
    )
    employee = await graphql_client._testing__create_employee(
        given_name="Opus", surname="Unmanaged", cpr_number=CPRNumber("2512480011")
    )
    await _create_engagement(graphql_client, class_uuids, "12345", employee.uuid, ou)
    return ou


@pytest.fixture
async def opus_nested_tree(
    graphql_client: GraphQLClient, class_uuids: dict[str, UUID]
) -> UUID:
    """
    OPUS, a parent unit with an engagement of its own and a child unit that also
    has one. Returns the *parent*, so processing has to recurse into the child.
    """
    parent = await _create_ou(
        graphql_client, class_uuids, "OPUS nested parent", "sn_opus_nested_parent"
    )
    parent_employee = await graphql_client._testing__create_employee(
        given_name="Opus", surname="ParentEmployee", cpr_number=CPRNumber("2512480012")
    )
    await _create_engagement(
        graphql_client, class_uuids, "11111", parent_employee.uuid, parent
    )
    manager = await graphql_client._testing__create_employee(
        given_name="Opus", surname="NestedManager", cpr_number=CPRNumber("2512480013")
    )
    await _create_manager(graphql_client, class_uuids, "54321", manager.uuid, parent)

    child = await _create_ou(
        graphql_client,
        class_uuids,
        "OPUS nested child",
        "sn_opus_nested_child",
        parent=parent,
    )
    child_employee = await graphql_client._testing__create_employee(
        given_name="Opus", surname="ChildEmployee", cpr_number=CPRNumber("2512480014")
    )
    await _create_engagement(
        graphql_client, class_uuids, "22222", child_employee.uuid, child
    )
    return parent


@pytest.fixture
async def sd_ambiguous_tree(
    graphql_client: GraphQLClient, class_uuids: dict[str, UUID]
) -> UUID:
    """
    SD, the manager has two engagements of an allowed type and the manager role
    has *no* linked engagement, so the fallback cannot pick one and the manager
    engagement number is left empty.
    """
    ou = await _create_ou(
        graphql_client, class_uuids, "SD ambiguous", "sn_sd_ambiguous"
    )
    employee = await graphql_client._testing__create_employee(
        given_name="Sd", surname="AmbEmployee", cpr_number=CPRNumber("2512480015")
    )
    await _create_engagement(graphql_client, class_uuids, "XY-90001", employee.uuid, ou)
    manager = await graphql_client._testing__create_employee(
        given_name="Sd", surname="AmbManager", cpr_number=CPRNumber("2512480016")
    )
    await _create_engagement(graphql_client, class_uuids, "XY-90002", manager.uuid, ou)
    await _create_engagement(graphql_client, class_uuids, "XY-90003", manager.uuid, ou)
    # No engagement link and two candidates -> ambiguous, so no manager number.
    await _create_manager(graphql_client, class_uuids, "sd-amb-mgr", manager.uuid, ou)
    return ou


@pytest.fixture
async def med_tree(graphql_client: GraphQLClient, class_uuids: dict[str, UUID]) -> UUID:
    """
    A MED tree: a root unit whose association carries a trade union (reported as
    Hovedorganisation) and a child unit whose association does not. Both use the
    composite "TR, næstformand" role, so each association yields two rows.
    """
    root = await _create_ou(graphql_client, class_uuids, "SafetyNet MED", "sn_med_root")
    root_person = await graphql_client._testing__create_employee(
        given_name="Med", surname="Rep", cpr_number=CPRNumber("2512480020")
    )
    await _create_association(
        graphql_client,
        class_uuids,
        "med-root-ass",
        root_person.uuid,
        root,
        trade_union=class_uuids["LO"],
    )

    child = await _create_ou(
        graphql_client, class_uuids, "MED child", "sn_med_child", parent=root
    )
    child_person = await graphql_client._testing__create_employee(
        given_name="Med", surname="ChildRep", cpr_number=CPRNumber("2512480021")
    )
    # No trade union -> Hovedorganisation is empty.
    await _create_association(
        graphql_client, class_uuids, "med-child-ass", child_person.uuid, child
    )
    return root
