# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
from typing import Annotated

from fastapi import Depends
from fastramqpi.depends import from_user_context
from fastramqpi.ramqp.depends import from_context

from safetynet.autogenerated_graphql_client import GraphQLClient as _GraphQLClient

from .config import SafetyNetSettings as _Settings

# The authenticated MO GraphQL client lives in FastRAMQPI's own app-level context
# (populated because we pass `graphql_client_cls=GraphQLClient` to FastRAMQPI).
GraphQLClient = Annotated[_GraphQLClient, Depends(from_context("graphql_client"))]

# Our own settings object is added via `fastramqpi.add_context(settings=...)`,
# which lands in the user context.
Settings = Annotated[_Settings, Depends(from_user_context("settings"))]
