# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
from typing import Any
from uuid import UUID

import structlog
from fastapi import APIRouter
from fastapi import FastAPI
from fastramqpi.main import FastRAMQPI
from starlette.status import HTTP_200_OK

from . import depends
from .autogenerated_graphql_client import GraphQLClient
from .config import SafetyNetSettings
from .safetynet import generate_reports

logger = structlog.get_logger()

# The MO GraphQL version the ariadne-codegen client is generated against.
# Remember to regenerate the client (`ariadne-codegen client`) and update the
# checked-in `schema.graphql` when bumping this.
GRAPHQL_VERSION = 30


def create_fastramqpi(**kwargs: Any) -> FastRAMQPI:
    settings = SafetyNetSettings(**kwargs)

    fastramqpi = FastRAMQPI(
        application_name="os2mo-safetynet",
        settings=settings.fastramqpi,
        graphql_client_cls=GraphQLClient,
        graphql_version=GRAPHQL_VERSION,
    )
    fastramqpi.add_context(settings=settings)

    fastapi_router = APIRouter()

    @fastapi_router.post("/trigger", status_code=HTTP_200_OK)
    async def trigger(
        gql_client: depends.GraphQLClient,
        settings: depends.Settings,
        adm_unit_uuid: UUID | None = None,
        med_unit_uuid: UUID | None = None,
        skip_upload: bool = False,
        only_adm_org: bool = False,
    ) -> dict[str, int]:
        """
        Generate (and, unless `skip_upload`, SFTP-upload) the SafetyNet reports.

        Query parameters:
            adm_unit_uuid: root of the ADM org tree (defaults to the configured
                `safetynet_adm_unit_uuid`).
            med_unit_uuid: root of the MED org tree (defaults to the configured
                `safetynet_med_unit_uuid`).
            skip_upload: write CSVs to /tmp instead of uploading via SFTP.
            only_adm_org: only process the administrative organisation.
        """
        adm_unit = adm_unit_uuid or settings.safetynet_adm_unit_uuid
        med_unit = None
        if not only_adm_org:
            med_unit = med_unit_uuid or settings.safetynet_med_unit_uuid
            if med_unit is None:
                raise ValueError(
                    "med_unit_uuid must be provided (or configured) unless "
                    "only_adm_org is set"
                )

        logger.info(
            "Triggered SafetyNet report generation",
            adm_unit_uuid=str(adm_unit),
            med_unit_uuid=str(med_unit),
            skip_upload=skip_upload,
            only_adm_org=only_adm_org,
        )
        return await generate_reports(
            gql_client=gql_client,
            settings=settings,
            adm_unit_uuid=adm_unit,
            med_unit_uuid=med_unit,
            skip_upload=skip_upload,
            only_adm_org=only_adm_org,
        )

    app = fastramqpi.get_app()
    app.include_router(fastapi_router)

    return fastramqpi


def create_app(**kwargs: Any) -> FastAPI:
    fastramqpi = create_fastramqpi(**kwargs)
    return fastramqpi.get_app()
