# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
# This module generates 4 reports (CSV files) and uploads these to
# Safetynet via SFTP. The reports are
# 1) An engagements report for the ADM organisation
# 2) An org unit report for the ADM organisation
# 3) An association report for the MED organisation
# 4) An org unit report for the MED organisation
#
# The reports are generated by reading data from OS2mo over GraphQL. The
# GraphQL client is the ariadne-codegen generated `GraphQLClient` (see
# `queries.graphql` / `autogenerated_graphql_client/`), so all responses are
# typed pydantic models rather than dicts.
#
# NOTE: the attribute access below follows the shape of `queries.graphql`. The
# exact generated class/field names are produced by `ariadne-codegen` and may
# need minor fixups the first time the client is generated against a real MO
# schema.
import csv
import datetime
from contextlib import contextmanager
from io import BytesIO
from io import StringIO
from typing import Iterator
from uuid import UUID

import structlog
from more_itertools import first
from more_itertools import last
from more_itertools import one
from more_itertools import only
from paramiko import AutoAddPolicy
from paramiko import SFTPClient
from paramiko import SSHClient
from pydantic.main import BaseModel
from starlette.concurrency import run_in_threadpool

from safetynet.autogenerated_graphql_client import GetAdmUnitOrgUnitsObjectsCurrent
from safetynet.autogenerated_graphql_client import (
    GetEngagementEngagementsObjectsCurrent,
)
from safetynet.autogenerated_graphql_client import (
    GetEngagementEngagementsObjectsCurrentManagers,
)
from safetynet.autogenerated_graphql_client import GraphQLClient
from safetynet.config import SafetyNetSettings
from safetynet.config import SafetyNetSFTP
from safetynet.config import SourceSystem

DATE_FORMAT = "%Y-%m-%d"

logger = structlog.get_logger()


class AdmEngRow(BaseModel):
    """
    Data model for the ADM engagement report
    """

    person_user_key: str
    cpr: str
    first_name: str
    last_name: str
    email: str
    org_unit: UUID
    eng_start: str
    eng_end: str
    manager_eng_user_key: str
    manager_cpr: str
    username: str  # AD username
    job_function: str


class AdmOuRow(BaseModel):
    """
    Data model for the ADM org unit report
    """

    name: str
    uuid: UUID
    parent: UUID | None
    pnumber: str
    related_units: list[UUID]


class MedAssRow(BaseModel):
    """
    Data model for the MED association report
    """

    cpr: str
    org_unit: UUID
    ass_start: str
    ass_end: str
    role: str
    main_org: str


class MedOuRow(BaseModel):
    """
    Data model for the MED org unit report
    """

    name: str
    uuid: UUID
    parent: UUID | None


def _format_date(value: datetime.datetime) -> str:
    """
    Format a MO validity datetime as a `YYYY-MM-DD` string.
    """
    return value.strftime(DATE_FORMAT)


def _format_end_date(value: datetime.datetime | None) -> str:
    """
    Format a MO validity *end* as the last day the object is valid.

    MO stores validities as half-open intervals, and from GraphQL v29 it returns
    `validity.to` unadjusted, i.e. as midnight of the day *after* the last valid
    day. Up to v28 it subtracted a minute before truncating to a date, so the
    same engagement read at v22 and at v30 differs by a day. SafetyNet expects
    the inclusive day, so subtract it back off here.

    Done in date arithmetic rather than on the datetime, so that a DST boundary
    cannot shift the result.
    """
    if value is None:
        return ""
    return (value.date() - datetime.timedelta(days=1)).strftime(DATE_FORMAT)


def _remove_sd_user_key_prefix(user_key: str) -> str:
    """
    Remove SD InstitutionIdentifier prefix from user_key if present. I.e. the function
    will return 12345 for both user_key=XY-12345 and user_key=12345.

    If the user_key is a UUID (string), that string will just be returned.

    Args:
        user_key: the (employee or manager) engagement user_key.

    Returns:
        The user_key without the SD InstitutionIdentifier prefix.
    """
    try:
        UUID(user_key)
    except ValueError:
        pass
    else:
        return user_key

    if not user_key.count("-") == 1:
        return user_key

    return last(user_key.split("-"))


async def get_opus_manager_eng_user_key_and_cpr(
    gql_client: GraphQLClient,
    org_unit: GetAdmUnitOrgUnitsObjectsCurrent,
    employee_eng_user_key: str,
) -> tuple[str, str]:
    manager = only(org_unit.managers)
    if manager is None:
        return "", ""

    manager_person = only(manager.person or [])
    manager_cpr = (manager_person.cpr_number or "") if manager_person else ""

    # The manager user_key is the same as the engagement user_key
    manager_eng_user_key = manager.user_key or ""

    # If the manager is the employee itself, use the manager of the parent units
    if manager_eng_user_key == employee_eng_user_key:
        parent_ou_resp = await gql_client.get_parent_manager(org_unit=[org_unit.uuid])
        parent_ou = one(parent_ou_resp.objects)
        parent_current = parent_ou.current
        parent = parent_current.parent if parent_current is not None else None
        parent_manager = only(parent.managers) if parent is not None else None
        manager_eng_user_key = (parent_manager.user_key or "") if parent_manager else ""

    return manager_eng_user_key, manager_cpr


def _get_sd_manager_eng_user_key(
    manager: GetEngagementEngagementsObjectsCurrentManagers,
    allowed_engagement_types: list[str],
) -> str:
    person = only(manager.person or [])
    engagements = person.engagements if person else []

    eng_response = manager.engagement_response
    if eng_response is not None and eng_response.current is not None:
        return eng_response.current.user_key

    try:
        manager_eng_user_key = one(
            eng.user_key
            for eng in engagements
            if eng.engagement_type.user_key in allowed_engagement_types
        )
    except ValueError:
        logger.warning(
            "No manager-engagement coupling and more than one manager engagement",
            person=person,
        )
        return ""
    else:
        return manager_eng_user_key


def get_sd_manager_eng_user_key_and_cpr(
    settings: SafetyNetSettings,
    engagement: GetEngagementEngagementsObjectsCurrent,
) -> tuple[str, str]:
    manager = only(engagement.managers)
    if manager is None:
        return "", ""

    manager_person = only(manager.person or [])
    manager_cpr = (manager_person.cpr_number or "") if manager_person else ""

    manager_eng_user_key = _get_sd_manager_eng_user_key(
        manager, settings.allowed_sd_engagement_types
    )

    return _remove_sd_user_key_prefix(manager_eng_user_key), manager_cpr


async def get_manager_eng_user_key_and_cpr(
    gql_client: GraphQLClient,
    settings: SafetyNetSettings,
    current_unit: GetAdmUnitOrgUnitsObjectsCurrent,
    current_engagement: GetEngagementEngagementsObjectsCurrent,
) -> tuple[str, str]:
    """
    State/strategy pattern for getting the managers engagement user_key.
    """
    if settings.source_system == SourceSystem.OPUS:
        return await get_opus_manager_eng_user_key_and_cpr(
            gql_client=gql_client,
            org_unit=current_unit,
            employee_eng_user_key=current_engagement.user_key or "",
        )
    elif settings.source_system == SourceSystem.SD:
        return get_sd_manager_eng_user_key_and_cpr(
            settings=settings,
            engagement=current_engagement,
        )
    else:
        # Unreachable: `SourceSystem` has no other members, but mypy needs the
        # branch to see that the function always returns.
        raise NotImplementedError()  # pragma: no cover


async def process_engagement(
    gql_client: GraphQLClient,
    settings: SafetyNetSettings,
    eng_uuid: UUID,
    org_unit: GetAdmUnitOrgUnitsObjectsCurrent,
) -> AdmEngRow:
    """
    Process a single engagement from an ADM org unit

    Args:
        gql_client: the GraphQL client
        settings: the application settings
        eng_uuid: the UUID of the engagement
        org_unit: the "current" org unit (typed GraphQL object)

    Returns:
        Data for the engagement
    """
    logger.debug("Processing engagement", uuid=str(eng_uuid))

    engagement = await gql_client.get_engagement(uuid=[eng_uuid])

    obj = one(engagement.objects)

    eng_start = _format_date(first(obj.validities).validity.from_)
    eng_end = _format_end_date(last(obj.validities).validity.to)

    current = obj.current
    assert current is not None
    person = one(current.person)
    email_address = first(person.addresses, None)
    email = email_address.value if email_address is not None else ""
    cpr = person.cpr_number or ""

    manager_eng_user_key, manager_cpr = await get_manager_eng_user_key_and_cpr(
        gql_client=gql_client,
        settings=settings,
        current_unit=org_unit,
        current_engagement=current,
    )

    return AdmEngRow(
        # TODO: handle variability with a proper strategy pattern if more than two cases
        #       are required
        person_user_key=current.user_key
        if settings.source_system == SourceSystem.OPUS
        else _remove_sd_user_key_prefix(current.user_key),
        cpr=cpr,
        first_name=person.given_name,
        last_name=person.surname,
        email=email,
        org_unit=org_unit.uuid,
        eng_start=eng_start,
        eng_end=eng_end,
        manager_eng_user_key=manager_eng_user_key,
        manager_cpr=manager_cpr if not manager_cpr == cpr else "",
        username=first(email.split("@")),
        job_function=current.job_function.name,
    )


async def process_adm_unit(
    gql_client: GraphQLClient,
    settings: SafetyNetSettings,
    org_unit: UUID,
    adm_eng_rows: list[AdmEngRow],
    adm_ou_rows: list[AdmOuRow],
) -> tuple[list[AdmEngRow], list[AdmOuRow]]:
    """
    Recursive function for processing the OU data and engagement data in an
    org unit from the ADM organisation. The function will traverse the entire
    OU-tree from the provided root node.

    Args:
        gql_client: the GraphQL client
        settings: the application settings
        org_unit: the root org unit to process
        adm_eng_rows: list of engagement data to append new data to
        adm_ou_rows: list of OU data to append new data to

    Returns:
        List of engagement data and list of OU data
    """
    logger.info("Processing adm unit", uuid=str(org_unit))

    unit = await gql_client.get_adm_unit(org_unit=[org_unit])
    current = one(unit.objects).current
    assert current is not None

    # Engagement data
    engs = [eng.uuid for eng in current.engagements]
    children = [child.uuid for child in current.children]

    # Org unit data
    parent_uuid = current.parent.uuid if current.parent is not None else None
    pnumber_address = only(current.addresses)
    pnumber = pnumber_address.value if pnumber_address is not None else ""

    related_unit_uuids = [
        related_ou.uuid
        for rel_unit in current.related_units
        for related_ou in rel_unit.org_units
        if not related_ou.uuid == current.uuid
    ]
    adm_ou_row = AdmOuRow(
        name=current.name or "",
        uuid=current.uuid,
        parent=parent_uuid,
        pnumber=pnumber,
        related_units=related_unit_uuids,
    )

    adm_ou_rows.append(adm_ou_row)

    for eng in engs:
        adm_eng_row = await process_engagement(gql_client, settings, eng, current)
        adm_eng_rows.append(adm_eng_row)

    for child in children:
        await process_adm_unit(gql_client, settings, child, adm_eng_rows, adm_ou_rows)

    return adm_eng_rows, adm_ou_rows


async def process_association(
    gql_client: GraphQLClient, ass_uuid: UUID, ou_uuid: UUID
) -> list[MedAssRow]:
    """
    Process a single association from a MED org unit

    Args:
        gql_client: the GraphQL client
        ass_uuid: the UUID of the association
        ou_uuid: the UUID of the org unit

    Returns:
        Data for the association
    """
    logger.debug("Processing association", uuid=str(ass_uuid))

    association = await gql_client.get_association(uuid=[ass_uuid])

    obj = one(association.objects)

    ass_start = _format_date(first(obj.validities).validity.from_)
    ass_end = _format_end_date(last(obj.validities).validity.to)

    current = obj.current
    assert current is not None
    person = only(current.person)
    cpr = (person.cpr_number or "") if person else ""

    dynamic_class = current.dynamic_class
    main_org = dynamic_class.name if dynamic_class is not None else ""
    # There must be two rows (Redmine case #63407) for composite roles, e.g.
    # "TR, næstformand" will be split into two rows - one for "TR" and one for
    # "næstformand"
    association_name = (
        current.association_type.name if current.association_type is not None else ""
    )
    roles = [role.strip() for role in association_name.split(",")]

    return [
        MedAssRow(
            cpr=cpr,
            org_unit=ou_uuid,
            ass_start=ass_start,
            ass_end=ass_end,
            role=role,
            main_org=main_org,
        )
        for role in roles
    ]


async def process_med_unit(
    gql_client: GraphQLClient,
    org_unit_uuid: UUID,
    med_ass_rows: list[MedAssRow],
    med_ou_rows: list[MedOuRow],
) -> tuple[list[MedAssRow], list[MedOuRow]]:
    """
    Recursive function for processing the OU data and association data in an
    org unit from the MED organisation. The function will traverse the entire
    OU-tree from the provided root node.

    Args:
        gql_client: the GraphQL client
        org_unit_uuid: the root org unit to process
        med_ass_rows: list of association data to append new data to
        med_ou_rows: list of OU data to append new data to

    Returns:
        List of association data and list of OU data
    """
    logger.info("Processing med unit", uuid=str(org_unit_uuid))

    unit = await gql_client.get_med_unit(org_unit=[org_unit_uuid])
    current = one(unit.objects).current
    assert current is not None

    # Association data
    assocs = [ass.uuid for ass in current.associations]
    children = [child.uuid for child in current.children]

    # Org unit data
    parent_uuid = current.parent.uuid if current.parent is not None else None
    med_ou_row = MedOuRow(
        name=current.name or "",
        uuid=current.uuid,
        parent=parent_uuid,
    )

    med_ou_rows.append(med_ou_row)

    for ass in assocs:
        ass_rows = await process_association(gql_client, ass, org_unit_uuid)
        med_ass_rows.extend(ass_rows)

    for child in children:
        await process_med_unit(gql_client, child, med_ass_rows, med_ou_rows)

    return med_ass_rows, med_ou_rows


def _serialize_csv(fieldnames: list[str], rows: list[dict[str, str]]) -> list[str]:
    """
    Serialize rows to the SafetyNet CSV format (``||``-delimited lines).

    Python's :mod:`csv` only supports single-character delimiters, so we write
    with ``|`` via :class:`csv.DictWriter` and expand it to the SafetyNet ``||``
    delimiter afterwards. This relies on field values never containing a ``|``
    (true for CPR numbers, UUIDs, dates, names and user keys).
    """
    buffer = StringIO()
    writer = csv.DictWriter(
        buffer,
        fieldnames=fieldnames,
        delimiter="|",
        quoting=csv.QUOTE_NONE,
        escapechar="\\",
        lineterminator="\n",
    )
    writer.writeheader()
    writer.writerows(rows)
    return buffer.getvalue().replace("|", "||").splitlines(keepends=True)


def adm_eng_rows_to_csv_lines(
    rows: list[AdmEngRow], include_manager_cpr: bool
) -> list[str]:
    """
    Convert ADM engagement data models to CSV
    """
    fieldnames = [
        "Medarbejdernummer",
        "CPR",
        "Fornavn",
        "Efternavn",
        "Mail",
        "Afdelingskode",
        "Startdato",
        "Slutdato",
        "LedersMedarbejdernummer",
    ]
    if include_manager_cpr:
        fieldnames.append("LedersCPR")
    fieldnames += ["Brugernavn", "Titel", "Faggruppe"]

    csv_rows: list[dict[str, str]] = []
    for r in rows:
        csv_row = {
            "Medarbejdernummer": r.person_user_key,
            "CPR": r.cpr,
            "Fornavn": r.first_name,
            "Efternavn": r.last_name,
            "Mail": r.email,
            "Afdelingskode": str(r.org_unit),
            "Startdato": r.eng_start,
            "Slutdato": r.eng_end,
            "LedersMedarbejdernummer": r.manager_eng_user_key,
            "Brugernavn": r.username,
            "Titel": r.job_function,
            "Faggruppe": r.job_function,
        }
        if include_manager_cpr:
            csv_row["LedersCPR"] = r.manager_cpr
        csv_rows.append(csv_row)

    return _serialize_csv(fieldnames, csv_rows)


def med_ass_rows_to_csv_lines(rows: list[MedAssRow]) -> list[str]:
    """
    Convert MED association data models to CSV
    """
    fieldnames = [
        "CPR",
        "Afdelingskode",
        "Startdato",
        "Slutdato",
        "Hverv",
        "Hovedorganisation",
    ]
    csv_rows = [
        {
            "CPR": r.cpr,
            "Afdelingskode": str(r.org_unit),
            "Startdato": r.ass_start,
            "Slutdato": r.ass_end,
            "Hverv": r.role,
            "Hovedorganisation": r.main_org,
        }
        for r in rows
    ]
    return _serialize_csv(fieldnames, csv_rows)


def adm_ou_rows_to_csv_lines(rows: list[AdmOuRow]) -> list[str]:
    """
    Convert ADM org unit data models to CSV
    """
    fieldnames = [
        "Afdelingsnavn",
        "Afdelingskode",
        "Forældreafdelingskode",
        "Pnummer",
        "Arbejdsmiljøorganisationkode",
    ]
    csv_rows = [
        {
            "Afdelingsnavn": r.name,
            "Afdelingskode": str(r.uuid),
            "Forældreafdelingskode": str(r.parent) if r.parent is not None else "",
            "Pnummer": r.pnumber,
            "Arbejdsmiljøorganisationkode": ",".join(
                str(related_unit) for related_unit in r.related_units
            ),
        }
        for r in rows
    ]
    return _serialize_csv(fieldnames, csv_rows)


def med_ou_rows_to_csv_lines(rows: list[MedOuRow]) -> list[str]:
    """
    Convert MED org unit data models to CSV
    """
    fieldnames = ["Afdelingsnavn", "Afdelingskode", "Forældreafdelingskode"]
    csv_rows = [
        {
            "Afdelingsnavn": r.name,
            "Afdelingskode": str(r.uuid),
            "Forældreafdelingskode": str(r.parent) if r.parent is not None else "",
        }
        for r in rows
    ]
    return _serialize_csv(fieldnames, csv_rows)


def write_csv(path: str, lines: list[str]) -> None:
    with open(path, "w") as fp:
        fp.writelines(lines)


@contextmanager
def _ssh_client(
    hostname: str, port: int, username: str, password: str
) -> Iterator[SSHClient]:
    ssh_client = SSHClient()
    try:
        ssh_client.set_missing_host_key_policy(AutoAddPolicy())
        ssh_client.connect(
            hostname=hostname,
            port=port,
            username=username,
            password=password,
            look_for_keys=False,
        )
        yield ssh_client
    finally:
        ssh_client.close()


@contextmanager
def sftp_client(
    hostname: str, port: int, username: str, password: str
) -> Iterator[SFTPClient]:
    with _ssh_client(hostname, port, username, password) as ssh_client:
        sftp_client_: SFTPClient = ssh_client.open_sftp()
        try:
            yield sftp_client_
        finally:
            sftp_client_.close()


def _upload_csv_sync(
    safetynet_sftp: SafetyNetSFTP,
    remote_path: str,
    csv_lines: list[str],
) -> None:
    # SFTP transfers bytes; encode as UTF-8 so the Danish column headers survive.
    upload_bytes = "".join(csv_lines).encode("utf-8")
    with sftp_client(
        safetynet_sftp.hostname,
        safetynet_sftp.port,
        safetynet_sftp.username,
        safetynet_sftp.password.get_secret_value(),
    ) as client:
        client.putfo(BytesIO(upload_bytes), remote_path, confirm=False)


async def upload_csv(
    safetynet_sftp: SafetyNetSFTP | None,
    remote_path: str,
    csv_lines: list[str],
) -> None:
    if safetynet_sftp is None:
        logger.warning("SFTP server settings missing - skipping upload!")
        return
    # paramiko is blocking, so run it off the event loop.
    await run_in_threadpool(_upload_csv_sync, safetynet_sftp, remote_path, csv_lines)


async def generate_reports(
    gql_client: GraphQLClient,
    settings: SafetyNetSettings,
    adm_unit_uuid: UUID,
    med_unit_uuid: UUID | None,
    skip_upload: bool,
    only_adm_org: bool,
) -> dict[str, int]:
    """
    Generate the SafetyNet reports and upload them via SFTP (unless skipped).

    Returns a summary of the number of rows in each generated report.
    """
    logger.info("Started Safetynet report generation")

    # Adm employee report
    logger.info("Generating adm employee report")
    adm_eng_rows, adm_ou_rows = await process_adm_unit(
        gql_client, settings, adm_unit_uuid, [], []
    )
    csv_lines = adm_eng_rows_to_csv_lines(adm_eng_rows, settings.include_manager_cpr)
    if skip_upload:
        write_csv("/tmp/adm-engagements.csv", csv_lines)
    else:
        await upload_csv(settings.safetynet_sftp, "adm-engagements.csv", csv_lines)

    med_ass_rows: list[MedAssRow] = []
    med_ou_rows: list[MedOuRow] = []
    if not only_adm_org:
        assert med_unit_uuid is not None
        # Med employee (based on associations) report
        logger.info("Generating med association report")
        med_ass_rows, med_ou_rows = await process_med_unit(
            gql_client, med_unit_uuid, [], []
        )
        csv_lines = med_ass_rows_to_csv_lines(med_ass_rows)
        if skip_upload:
            write_csv("/tmp/med-associations.csv", csv_lines)
        else:
            await upload_csv(settings.safetynet_sftp, "med-associations.csv", csv_lines)

    # Adm OU report
    logger.info("Generating adm OU report")
    csv_lines = adm_ou_rows_to_csv_lines(adm_ou_rows)
    if skip_upload:
        write_csv("/tmp/adm-org-units.csv", csv_lines)
    else:
        await upload_csv(settings.safetynet_sftp, "adm-org-units.csv", csv_lines)

    if not only_adm_org:
        # Med OU report
        logger.info("Generating MED OU report")
        csv_lines = med_ou_rows_to_csv_lines(med_ou_rows)
        if skip_upload:
            write_csv("/tmp/med-org-units.csv", csv_lines)
        else:
            await upload_csv(settings.safetynet_sftp, "med-org-units.csv", csv_lines)

    logger.info("Finished Safetynet report generation")

    return {
        "adm_engagements": len(adm_eng_rows),
        "adm_org_units": len(adm_ou_rows),
        "med_associations": len(med_ass_rows),
        "med_org_units": len(med_ou_rows),
    }
